# Generated by Django 4.2.6 on 2023-12-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_rename_protocole_servico_protocolo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='servicos_adicionais',
        ),
    ]
